<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="10" passed="10">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="80" started-at="2015-01-14T11:27:02Z" finished-at="2015-01-14T11:27:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="80" started-at="2015-01-14T11:27:02Z" finished-at="2015-01-14T11:27:02Z">
      <class name="com.extended.list.ExtendedListUnitTest">
        <test-method status="PASS" signature="testAddGetSize()[pri:0, instance:com.extended.list.ExtendedListUnitTest@121bcc9f]" name="testAddGetSize" duration-ms="19" started-at="2015-01-14T13:27:02Z" finished-at="2015-01-14T13:27:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddGetSize -->
        <test-method status="PASS" signature="testAllocateBucket()[pri:0, instance:com.extended.list.ExtendedListUnitTest@121bcc9f]" name="testAllocateBucket" duration-ms="1" started-at="2015-01-14T13:27:02Z" finished-at="2015-01-14T13:27:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAllocateBucket -->
        <test-method status="PASS" signature="testCompleteWrite()[pri:0, instance:com.extended.list.ExtendedListUnitTest@121bcc9f]" name="testCompleteWrite" duration-ms="1" started-at="2015-01-14T13:27:02Z" finished-at="2015-01-14T13:27:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCompleteWrite -->
        <test-method status="PASS" signature="testGetBucket()[pri:0, instance:com.extended.list.ExtendedListUnitTest@121bcc9f]" name="testGetBucket" duration-ms="0" started-at="2015-01-14T13:27:02Z" finished-at="2015-01-14T13:27:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetBucket -->
        <test-method status="PASS" signature="testGetIndexInBucket()[pri:0, instance:com.extended.list.ExtendedListUnitTest@121bcc9f]" name="testGetIndexInBucket" duration-ms="1" started-at="2015-01-14T13:27:02Z" finished-at="2015-01-14T13:27:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetIndexInBucket -->
        <test-method status="PASS" signature="testGetIndexOutOfBounds()[pri:0, instance:com.extended.list.ExtendedListUnitTest@121bcc9f]" name="testGetIndexOutOfBounds" duration-ms="1" started-at="2015-01-14T13:27:02Z" finished-at="2015-01-14T13:27:02Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException
	at com.extended.list.ExtendedList.get(ExtendedList.java:141)
	at com.extended.list.ExtendedListUnitTest.testGetIndexOutOfBounds(ExtendedListUnitTest.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetIndexOutOfBounds -->
        <test-method status="PASS" signature="testIndexInLessBucket()[pri:0, instance:com.extended.list.ExtendedListUnitTest@121bcc9f]" name="testIndexInLessBucket" duration-ms="1" started-at="2015-01-14T13:27:02Z" finished-at="2015-01-14T13:27:02Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at com.extended.list.ExtendedList.getIndexInBucket(ExtendedList.java:73)
	at com.extended.list.ExtendedListUnitTest.testIndexInLessBucket(ExtendedListUnitTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIndexInLessBucket -->
        <test-method status="PASS" signature="testIndexInMoreBucket()[pri:0, instance:com.extended.list.ExtendedListUnitTest@121bcc9f]" name="testIndexInMoreBucket" duration-ms="3" started-at="2015-01-14T13:27:02Z" finished-at="2015-01-14T13:27:02Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at com.extended.list.ExtendedList.getIndexInBucket(ExtendedList.java:67)
	at com.extended.list.ExtendedListUnitTest.testIndexInMoreBucket(ExtendedListUnitTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIndexInMoreBucket -->
        <test-method status="PASS" signature="testLessIndexInBucket()[pri:0, instance:com.extended.list.ExtendedListUnitTest@121bcc9f]" name="testLessIndexInBucket" duration-ms="1" started-at="2015-01-14T13:27:02Z" finished-at="2015-01-14T13:27:02Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at com.extended.list.ExtendedList.getIndexInBucket(ExtendedList.java:67)
	at com.extended.list.ExtendedListUnitTest.testLessIndexInBucket(ExtendedListUnitTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLessIndexInBucket -->
        <test-method status="PASS" signature="testMoreIndexInBucket()[pri:0, instance:com.extended.list.ExtendedListUnitTest@121bcc9f]" name="testMoreIndexInBucket" duration-ms="2" started-at="2015-01-14T13:27:02Z" finished-at="2015-01-14T13:27:02Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at com.extended.list.ExtendedList.getIndexInBucket(ExtendedList.java:73)
	at com.extended.list.ExtendedListUnitTest.testMoreIndexInBucket(ExtendedListUnitTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMoreIndexInBucket -->
      </class> <!-- com.extended.list.ExtendedListUnitTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
